spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:32768/jwt-security
      username: postgres
      password: postgrespw
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_url: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect