INSERT INTO race (description) VALUES
('Abyssinian'),
('American Bobtail'),
('American Curl'),
('American Shorthair'),
('American Wirehair'),
('Balinese'),
('Bengal'),
('Birman'),
('Bombay'),
('British Shorthair'),
('Burmese'),
('Cornish Rex'),
('Devon Rex'),
('Egyptian Mau'),
('Exotic Shorthair'),
('Havana Brown'),
('Himalayan'),
('Japanese Bobtail'),
('Korat'),
('Maine Coon'),
('Manx'),
('Norwegian Forest Cat'),
('Oriental'),
('Persian'),
('Ragdoll'),
('Siamese'),
('Siberian'),
('Singapura'),
('Snowshoe'),
('Somali'),
('Sphynx'),
('Tonkinese'),
('Turkish Angora'),
('Turkish Van'),
('Affenpinscher'),
('Australian Cattle Dog'),
('Beagle'),
('Bichon Frise'),
('Border Collie'),
('Boston Terrier'),
('Boxer'),
('Bulldog'),
('Chihuahua'),
('Cocker Spaniel'),
('Dalmatian'),
('German Shepherd'),
('Golden Retriever'),
('Labrador Retriever'),
('Maltese'),
('Poodle'),
('Pug'),
('Rottweiler'),
('Siberian Husky'),
('West Highland White Terrier');